version: 2
jobs:
  deploy_stage:
    docker:
      - image: cimg/node:16.13.2
    environment:
      CI: false
    resource_class: large
    steps:
      - checkout
      - run: yarn up '@web3-onboard/*@next'
      - run: yarn install
      - run: yarn build-staging
      - run: touch .env
      - run: echo "REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID" > .env
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo-staging"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo-staging/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-staging"
  
  deploy_prod:
    docker:
      - image: cimg/node:16.13.2
    environment:
      CI: false
    resource_class: large
    steps:
      - checkout
      - run: yarn cache clean
      - run: yarn up '@web3-onboard/*@latest'
      - run: yarn install
      - run: yarn build
      - run: touch .env
      - run: echo "REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID" > .env
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/remove.sh reactdemo"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo"
workflows:
  version: 2
  test_build:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          filters:
            branches:
              only:
                - master
