version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.18.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
    deploy_stage:
      docker:
        - image: circleci/node:10.18.1-browsers
      steps:
        - checkout
        - run: yarn
        - run: yarn build-stage
        - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo-stage/
        - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-stage"
  deploy_prod:
    docker:
      - image: circleci/node:10.18.1-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo"
workflows:
  version: 2
  test_build:
    jobs:
    - deploy_stage:
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          filters:
            branches:
              only:
                - master
