version: 2
jobs:
  deploy_stage:
    docker:
      - image: circleci/node:10.18.1-browsers
    steps:
      - checkout
      - run: yarn cache clean && rm -r node_modules && yarn install
      - run: yarn build-staging
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo-staging/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-staging"
  deploy_prod:
    docker:
      - image: circleci/node:10.18.1-browsers
    steps:
      - checkout
      - run: yarn cache clean && rm -r node_modules && yarn install
      - run: yarn build
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* $EC2_PROD_USER@$EC2_PROD_IP:/home/ubuntu/reactdemo/
      - run: ssh -oStrictHostKeyChecking=no -v $EC2_PROD_USER@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo"
workflows:
  version: 2
  test_build:
    jobs:
      - deploy_stage:
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          filters:
            branches:
              only:
                - master
