name: React Demo Deploy Staging

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - feature/gh_actions_deploy
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - run: yarn setup-staging-w3o-env
      - run: yarn build-staging
        env:
          CI: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: touch .env
      - run: echo "REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID" > .env
      - run: ssh -oStrictHostKeyChecking=no -v ${{secrets.EC2_PROD_USER}}@${{secrets.EC2_PROD_IP}} "sh /home/ubuntu/remove.sh reactdemo-staging"
      - run: scp -oStrictHostKeyChecking=no -v -r /home/circleci/project/build/* ${{secrets.EC2_PROD_USER}}@${{secrets.EC2_PROD_IP}}:/home/ubuntu/reactdemo-staging/
      - run: ssh -oStrictHostKeyChecking=no -v ${{secrets.EC2_PROD_USER}}@$EC2_PROD_IP "sh /home/ubuntu/move.sh reactdemo-staging"